### PR TITLE
Updated CKE5 dev/dependencies to 35.2.1

### LINKED ISSUE #399: Bump the editor to the latest version
## 📝 Provide a description of the improvement

GH writer uses CKE5 at version `^35.1.0` currently. We have released a `^35.2.x` version recently so we should catch up.

## 📃 Other details

*   Browser: …
*   OS: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by mateuszzagorski**
Updated package.json file with never version of CKE5 dependencies and devdependencies. Closes #399.

### CODE REVIEW

**Review by mlewand — CHANGES_REQUESTED** [review]
Did you checked unit tests after this change?

The tests are failing, since the icons were moved in this release (that was a BC in this release).

**Comment by mateuszzagorski** [comment]
Yes I've run the tests, and the only one failing for me is the one from the savedreplies plugin -> `should insert the reply on user selection`.  
I wanted to talk about it and create an issue specifically to resolve it (as I wasn't able to fix it quickly) - since overall the bump does seem to work, and without this PR merged we will delay a bunch of others.   
  
So if you agree - I will extract the issue regarding test coverage and possibly we can merge this one as it is.

**Comment by mlewand** [comment]
That's odd. [As changelog say](https://github.com/ckeditor/ckeditor5/blob/master/CHANGELOG.md), we moved v35.2.0 the bold and paragraph icons to the core package:



If you browse current code, e.g. tests for kabab plugin ([permalink](https://github.com/ckeditor/github-writer/blob/84515ce8a5221ab46d9c1c97e79070b78f3000ca/tests/unit/plugins/kebab.js#L13)) it's using basic-styles package instead of core:



How is that possible, am I missing something?

**Comment by mlewand** [comment]
I added a commit fixing the icon paths. There's another issue #402 that I won't be able to do as a part of review so I extracted it.

**Pull request merged**
