### PR TITLE
Broken appearance

### LINKED ISSUE #480: Broken appearance
## 📝 Provide detailed reproduction steps (if any)

1. Open any GitHub issue and scroll to the comment editor.

### ✔️ Expected result

GitHub writer has a readable, visible UI.

### ❌ Actual result

UI is nearly invisible and the additional toolbar does not have any background. The issue is more prominent in any of the GH dark themes:
Screenshot 2024-04-03 at 12 46 18

### ❓ Possible solution

Probably styles for GH Writer should be updated.

## 📃 Other details

* Browser: Google Chrome 123.0.6312.87
* OS: macOS 14.4.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by illia-stv**
Updates css styles for fixing broken appearance. Closes: #480

### CODE REVIEW

**Comment by illia-stv** [comment]
After changes it should look like this:

**Review by mmotyczynska — COMMENTED** [review]
It looks better, but I'd suggest a few more improvements.

The editor content should have a different background. Compare the two:

**Original**



**GitHub Writer**:



The background should be the same colour as the `Write` tab. If we change this, it would be better for the dropdowns, which don't look good now because everything has the same background colour:  
 



Maybe we should also consider adding a border/outline to the dropdown so the user can see exactly where it ends.

We could also consider bumping the CKEditor version.

**Review by pszczesniak — COMMENTED** [review]
As far as i can see - `CSS` variables in `GitHub` were changed - for example:

from `--color-border-default` into `--borderColor-default`

Maybe would be good to just update those variables names and potentially this could fix the problem, WDYT?

**Review by pszczesniak — COMMENTED** [review]
I've tested it on latest `Chrome` and `Firefox` with `dark`/`light`/`auto` theme and all looks like it should 👍 

One thing we could update also - background in table in an even row:

https://github.com/ckeditor/github-writer/blob/ghw/480-broken-appearance/src/app/theme/content.css#L125

This variable can be changed into: `--bgColor-muted`.

**Comment by pszczesniak** [comment]
And this issue: #482 will be also closed by this PR :tada:

**Review by pszczesniak — APPROVED** [review]

**Review by mmotyczynska — APPROVED** [review]

**Pull request merged**
